### PR TITLE
Add Anumargak router for comparison

### PR DESCRIPTION
**Pull request by amitguptagwl**
Please accept the PR to add [Anumargak](https://github.com/NaturalIntelligence/anumargak) router. I've not updated the result on README because

* Somehow express was not being installed on my machine
* Everyone has different machine so different results..

However here is report from my machine (ubuntu 17.10, i7, 16GB, node v9.10.1, npm v5.8.0)

```
=======================
 find-my-way benchmark
=======================
short static: 10,498,625 ops/sec
static with same radix: 3,861,088 ops/sec
dynamic route: 1,366,492 ops/sec
mixed static dynamic: 1,952,055 ops/sec
long static: 6,146,350 ops/sec
wildcard: 2,720,057 ops/sec
all together: 462,154 ops/sec

=====================
 anumargak benchmark
=====================
short static: 20,731,932 ops/sec
static with same radix: 30,583,395 ops/sec
dynamic route: 9,088,856 ops/sec
mixed static dynamic: 4,029,118 ops/sec
long static: 31,527,839 ops/sec
wildcard: 3,538,916 ops/sec
all together: 1,312,540 ops/sec

================
 call benchmark
================
short static: 3,715,259 ops/sec
static with same radix: 3,802,896 ops/sec
dynamic route: 816,136 ops/sec
mixed static dynamic: 876,621 ops/sec
long static: 4,115,237 ops/sec
wildcard: 1,346,504 ops/sec
all together: 250,349 ops/sec

======================
 koa-router benchmark
======================
short static: 1,185,294 ops/sec
static with same radix: 1,217,684 ops/sec
dynamic route: 1,135,935 ops/sec
mixed static dynamic: 1,119,404 ops/sec
long static: 1,201,539 ops/sec
wildcard: 1,154,779 ops/sec
all together: 184,463 ops/sec

===========================
 koa-tree-router benchmark
===========================
short static: 13,596,453 ops/sec
static with same radix: 6,631,522 ops/sec
dynamic route: 3,232,589 ops/sec
mixed static dynamic: 3,835,127 ops/sec
long static: 8,316,111 ops/sec
wildcard: 4,428,353 ops/sec
all together: 864,198 ops/sec

===============================================
 router benchmark (WARNING: includes handling)
===============================================
short static: 1,186,380 ops/sec
static with same radix: 1,092,566 ops/sec
dynamic route: 692,150 ops/sec
mixed static dynamic: 612,234 ops/sec
long static: 621,997 ops/sec
wildcard: 497,708 ops/sec
all together: 114,670 ops/sec

=================
 routr benchmark
=================
short static: 3,795,356 ops/sec
static with same radix: 1,905,451 ops/sec
dynamic route: 838,607 ops/sec
mixed static dynamic: 541,265 ops/sec
long static: 407,290 ops/sec
wildcard: 327,995 ops/sec
all together: 101,198 ops/sec

=========================
 server-router benchmark
=========================
short static: 2,866,262 ops/sec
static with same radix: 2,854,169 ops/sec
dynamic route: 1,772,911 ops/sec
mixed static dynamic: 1,799,525 ops/sec
long static: 1,944,810 ops/sec
wildcard: 1,472,171 ops/sec
all together: 291,769 ops/sec

=======================
 trek-router benchmark
=======================
short static: 9,885,615 ops/sec
static with same radix: 5,112,651 ops/sec
dynamic route: 1,812,229 ops/sec
mixed static dynamic: 2,259,349 ops/sec
long static: 8,090,141 ops/sec
wildcard: 3,499,804 ops/sec
all together: 537,065 ops/sec

```

### CODE REVIEW

**Comment by amitguptagwl** [comment]
Any feedback over this PR?

**Comment by delvedor** [comment]
Hi! Sorry currently I'm very busy at work.
Since the results are very good I want to take some time to review the code.
I'll do that asap.

**Comment by amitguptagwl** [comment]
no problem. And thanks for your kind response.

**Comment by amitguptagwl** [comment]
Have you got the chance to look into?

**Comment by arthurfiorette** [comment]
Hi @delvedor, I've looked into `anumargak`, and it seems like a good fit for a lot of cool new projects. Is there any chance we can get this benchmark into this repo?

**Comment by amitguptagwl** [comment]
@arthurfiorette I'm the author of Anumargak. I believe we don't need such comparisons. I've written an article on this in past. Please have a look: https://amitgupta-gwl.medium.com/a-quick-guide-to-select-a-router-for-a-node-js-application-62c682e40afa

**Pull request closed without merging**
