### PR TITLE
Added "real world" benchmarks

### PR DESCRIPTION
**Pull request by delvedor**
This benchmarks aims to create a more "real world" situation.
Every benchmark is in a separate file because V8 will optimize the code during time, so having all the code in a single file is not very reliable.

Feedbacks?

cc @mcollina @hueniverse

### CODE REVIEW

**Comment by delvedor** [comment]
Sample output:
```
find-my-way benchmark
short dynamic: 592.903ms
mixed static dynamic: 899.620ms
short static: 138.498ms
long static: 202.201ms
all together: 1838.629ms

call benchmark
short dynamic: 977.113ms
mixed static dynamic: 1499.504ms
short static: 245.300ms
long static: 274.876ms
all together: 3163.552ms

express benchmark
short dynamic: 1347.273ms
mixed static dynamic: 1719.417ms
short static: 1171.166ms
long static: 1364.634ms
all together: 5903.385ms

koa benchmark
short dynamic: 3281.249ms
mixed static dynamic: 3181.007ms
short static: 3096.667ms
long static: 3094.930ms
all together: 12360.630ms
```

**Comment by mcollina** [comment]
Is it worth keeping the old ones?

In any case, LGTM

**Comment by delvedor** [comment]
I've updated the printed result, now it's in ops/sec:

```
find-my-way benchmark
short dynamic: 2,217,721 ops/sec
mixed static dynamic: 1,723,581 ops/sec
short static: 10,837,741 ops/sec
long static: 7,388,863 ops/sec
all together: 760,112 ops/sec

call benchmark
short dynamic: 1,105,202 ops/sec
mixed static dynamic: 589,798 ops/sec
short static: 3,230,688 ops/sec
long static: 3,005,355 ops/sec
all together: 287,646 ops/sec

express benchmark
short dynamic: 484,183 ops/sec
mixed static dynamic: 410,096 ops/sec
short static: 451,717 ops/sec
long static: 410,023 ops/sec
all together: 107,587 ops/sec

koa benchmark
short dynamic: 315,724 ops/sec
mixed static dynamic: 320,069 ops/sec
long static: 305,726 ops/sec
long static: 303,334 ops/sec
all together: 73,953 ops/sec
```

**Comment by delvedor** [comment]
> Is it worth keeping the old ones?

I don't think so, at this point we can use just these, but we should add the files and results for all the others routers :D

We should also add a test for wildcard routes as well, then we can use this test even inside the `find-my-way` repo :)

**Comment by mcollina** [comment]
Let’s port the other ones and let’s remove the old benchmarks.

**Comment by delvedor** [comment]
I think we should remove from the benchmarks [route-recognizer](https://github.com/tildeio/route-recognizer) and [radix-router](https://github.com/charlieduong94/radix-router), because they not support http methods handling. This benchmark should support only http routers.

What do you think?

**Review by mcollina — COMMENTED** [review]
+1

**Comment by hueniverse** [comment]
I don't think this is enough of a real world sample. You have a lot of dynamic paths and very few static. Every application I've worked on has something like this for GETs:

- `/user`
- `/user/comments`
- `/user/avatar`
- `/user/lookup/username/{username}`
- `/user/lookup/email/{address}`

Would be good to add more overlapping static routs with overlap at the 1st and 2nd segments as well as paths with 2-3 static segments with a dynamic one mixes (both as the last one and somewhere in the middle).

**Comment by mcollina** [comment]
LGTM as it’s good progress, but let’s capture Eran’s suggestions in an issue and tackle them in another PR.

**Comment by delvedor** [comment]
> LGTM as it’s good progress, but let’s capture Eran’s suggestions in an issue and tackle them in another PR.

Agree, this pr became huge, I'll open another pr for the static routes and for a 404 test case :)

**Pull request merged**
